services:
  frontend:
    image: my-angular-app
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    image: my-fastapi-app
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydb

  mongodb:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
